<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../include_fluxograma/class.xmlparser.php';

/**
 * Test class for XmlParser.
 * Generated by PHPUnit on 2010-06-13 at 18:10:22.
 */
class XmlParserTest extends PHPUnit_Framework_TestCase {
    /**
     * @var XmlParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new XmlParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testTag_open().
     */
    public function testTag_open() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testTag_close().
     */
    public function testTag_close() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCdata().
     */
    public function testCdata() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
